name: goreleaser

on:
  push:
    branches:
      - "release/*"
    tags:
      - "v*.*.*"
jobs:
  goreleaser:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: release dry run
        run: make release-dry-run
      - name: setup release environment
        run: |-
            echo 'GITHUB_TOKEN=${{secrets.GORELEASER_ACCESS_TOKEN}}' > .release-env
      - name: release publish
        run: make release